version: '3'

services:
  nginx:
    image: "rantan39/tapyrus-faucet-nginx:master"
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: tapyrus-faucet
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: nginx