version: '3.7'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      TAPYRUS_FAUCET_DATABASE_HOST: db
      TAPYRUS_FAUCET_DATABASE_PORT: 3306
      RAILS_ENV: development
    env_file:
      - .env
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/tapyrus-faucet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - "db:/var/lib/mysql"
volumes:
  db: