name: deploy

on: [pull_request]

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: create .env file
        run: |
          echo -e "RECAPTCHA_SITE_KEY=${{secrets.RECAPTCHA_SITE_KEY}}\n" >> .env
          echo -e "RECAPTCHA_SECRET_KEY=${{secrets.RECAPTCHA_SECRET_KEY}}\n" >> .env
          echo -e "TAPYRUS_RPC_FAUCET_USER=${{secrets.TAPYRUS_RPC_FAUCET_USER}}\n" >> .env
          echo -e "TAPYRUS_RPC_FAUCET_PASSWORD=${{secrets.TAPYRUS_RPC_FAUCET_PASSWORD}}\n" >> .env
          echo -e "TAPYRUS_HOST=${{secrets.TAPYRUS_HOST}}\n" >> .env
          echo -e "TAPYRUS_PORT=${{secrets.TAPYRUS_PORT}}\n" >> .env
          echo -e "MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}\n" >> .env
          echo -e "MYSQL_PASSWORD=${{secrets.MYSQL_PASSWORD}}\n" >> .env
          echo -e "TAPYRUS_FAUCET_DATABASE_PASSWORD=${{secrets.TAPYRUS_FAUCET_DATABASE_PASSWORD}}\n" >> .env
          echo -e "SECRET_KEY_BASE=${{secrets.SECRET_KEY_BASE}}\n" >> .env
      - name: build docker images
        run: |
          docker login --username rantan39 --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -f Dockerfile-production -t rantan39/tapyrus-faucet:master .
          docker build -f Dockerfile-nginx -t rantan39/tapyrus-faucet-nginx:master .
          docker push rantan39/tapyrus-faucet:master
          docker push rantan39/tapyrus-faucet-nginx:master
  deploy:
    name: Deploy testnet faucet
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: install ecs-cli
        run: |
          curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          chmod a+x /usr/local/bin/ecs-cli
      - name: deploy
        run: |
          ecs-cli compose --project-name tapyrus-faucet --file docker-compose-production.yml service up --create-log-groups --cluster-config tapyrus --ecs-profile tapyrus-profile --target-group-arn arn:aws:elasticloadbalancing:ap-northeast-1:104420014930:targetgroup/tapyrus-faucet/ee474c92d3834903 --container-name app --container-port 3000
          ecs-cli compose --project-name tapyrus-faucet-nginx --file docker-compose-production2.yml service up --create-log-groups --cluster-config tapyrus --ecs-profile tapyrus-profile --target-group-arn arn:aws:elasticloadbalancing:ap-northeast-1:104420014930:targetgroup/tapyrus-faucet-assets/02ad31e020260624 --container-name nginx --container-port 80